name: 'sumup_thc'
version: '1.0.0'

profile: 'sumup-thc'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  sumup_thc:
    # Config indicated by + and applies to all files under models/example/
    staging:
      +materialized: ephemeral
      +schema: staging
    intermediate:
      +materialized: incremental
      +schema: intermediate
    mart:
      +materialized: view
      +schema: mart
